name: GitHub release

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt install -y docker-compose

      - name: Flet pack
        run: docker-compose run app flet pack image.py --name "image" --product-name "image" 

      - name: Create release
        run: gh release create v$( date +'%Y%m%d%H%M%S' ) $( find * -name image )
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
